"""empty message

Revision ID: 1d7bd2a87389
Revises: 51759082cfc6
Create Date: 2021-03-01 14:10:18.911442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d7bd2a87389'
down_revision = '51759082cfc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('Transport_bonus', sa.Boolean(), nullable=False))
    op.add_column('worker', sa.Column('sales_commissions', sa.Boolean(), nullable=False))
    op.add_column('worker', sa.Column('variable_salary', sa.String(length=120), nullable=False))
    op.drop_index('varaible_salary', table_name='worker')
    op.create_unique_constraint(None, 'worker', ['variable_salary'])
    op.drop_column('worker', 'varaible_salary')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('varaible_salary', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'worker', type_='unique')
    op.create_index('varaible_salary', 'worker', ['varaible_salary'], unique=True)
    op.drop_column('worker', 'variable_salary')
    op.drop_column('worker', 'sales_commissions')
    op.drop_column('worker', 'Transport_bonus')
    # ### end Alembic commands ###
