"""empty message

Revision ID: 68f68c7930b6
Revises: 466124be3511
Create Date: 2021-03-29 14:12:58.803856

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68f68c7930b6'
down_revision = '466124be3511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'full_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'hashed_password',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'salt',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'user_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('worker', 'Consultor',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('worker', 'Estimated_annual_package',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('worker', 'Production_bonus',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('worker', 'Profit_Days',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('worker', 'Savings_Bank',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('worker', 'Transport_bonus',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('worker', 'Vacation_Bonus',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('worker', 'Vehicle_insurance',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('worker', 'actual_charge',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('worker', 'basic_salary',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('worker', 'candidate',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('worker', 'catchment_source',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('worker', 'cedula',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('worker', 'cesta_ticket',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('worker', 'coin',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('worker', 'company',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('worker', 'dinning_room',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('worker', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('worker', 'food_bags',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('worker', 'full_HCM_Emp_Family',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('worker', 'init_date',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('worker', 'interview_date',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('worker', 'life_insurance',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('worker', 'managment',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('worker', 'parking_payment',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('worker', 'partial_HCM_Emp_Family',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('worker', 'phone_number',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('worker', 'sector',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('worker', 'status',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('worker', 'vacant',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('worker', 'vacations',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('worker', 'variable_salary',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worker', 'variable_salary',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('worker', 'vacations',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('worker', 'vacant',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('worker', 'status',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('worker', 'sector',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('worker', 'phone_number',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('worker', 'partial_HCM_Emp_Family',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('worker', 'parking_payment',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('worker', 'managment',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('worker', 'life_insurance',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('worker', 'interview_date',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('worker', 'init_date',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('worker', 'full_HCM_Emp_Family',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('worker', 'food_bags',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('worker', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('worker', 'dinning_room',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('worker', 'company',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('worker', 'coin',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('worker', 'cesta_ticket',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('worker', 'cedula',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('worker', 'catchment_source',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('worker', 'candidate',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('worker', 'basic_salary',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('worker', 'actual_charge',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('worker', 'Vehicle_insurance',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('worker', 'Vacation_Bonus',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('worker', 'Transport_bonus',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('worker', 'Savings_Bank',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('worker', 'Profit_Days',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('worker', 'Production_bonus',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('worker', 'Estimated_annual_package',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('worker', 'Consultor',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('user', 'user_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'salt',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'full_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
