"""empty message

Revision ID: a730a536c85b
Revises: 
Create Date: 2021-03-02 19:24:44.368027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a730a536c85b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('salt', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('init_date', sa.String(length=80), nullable=False),
    sa.Column('Consultor', sa.String(length=80), nullable=False),
    sa.Column('candidate', sa.String(length=80), nullable=False),
    sa.Column('nationality', sa.String(length=80), nullable=False),
    sa.Column('cedula', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('catchment_source', sa.String(length=120), nullable=False),
    sa.Column('managment', sa.String(length=120), nullable=False),
    sa.Column('vacant', sa.String(length=120), nullable=False),
    sa.Column('branch_office', sa.String(length=120), nullable=False),
    sa.Column('interview_date', sa.String(length=120), nullable=False),
    sa.Column('Technical_Interview_date', sa.String(length=120), nullable=False),
    sa.Column('salary_offer_date', sa.String(length=120), nullable=False),
    sa.Column('preemployment_test_date', sa.String(length=120), nullable=False),
    sa.Column('References_Check_date', sa.String(length=120), nullable=False),
    sa.Column('admission_date', sa.String(length=120), nullable=False),
    sa.Column('current_employment_contract', sa.String(length=120), nullable=False),
    sa.Column('Participation_at_Softech', sa.Boolean(), nullable=False),
    sa.Column('Reason', sa.String(length=120), nullable=False),
    sa.Column('Salary_Aspirations', sa.String(length=120), nullable=False),
    sa.Column('Academic_level', sa.String(length=120), nullable=False),
    sa.Column('Place_of_residence', sa.String(length=120), nullable=False),
    sa.Column('experience_years', sa.String(length=120), nullable=False),
    sa.Column('availability', sa.String(length=120), nullable=False),
    sa.Column('Current_courses', sa.String(length=120), nullable=False),
    sa.Column('Software_Hardware_ERP_knowledge', sa.String(length=120), nullable=False),
    sa.Column('know_someone_company', sa.Boolean(), nullable=False),
    sa.Column('name_work_person', sa.String(length=120), nullable=False),
    sa.Column('actual_charge', sa.String(length=120), nullable=False),
    sa.Column('company', sa.String(length=120), nullable=False),
    sa.Column('sector', sa.String(length=120), nullable=False),
    sa.Column('coin', sa.String(length=120), nullable=False),
    sa.Column('basic_salary', sa.String(length=120), nullable=False),
    sa.Column('variable_salary', sa.String(length=120), nullable=False),
    sa.Column('cesta_ticket', sa.String(length=120), nullable=False),
    sa.Column('Monthly_Cash_Flow', sa.String(length=120), nullable=False),
    sa.Column('Profit_Days', sa.String(length=120), nullable=False),
    sa.Column('vacations', sa.String(length=120), nullable=False),
    sa.Column('Vacation_Bonus', sa.String(length=120), nullable=False),
    sa.Column('Factor', sa.String(length=120), nullable=False),
    sa.Column('Estimated_annual_package', sa.String(length=120), nullable=False),
    sa.Column('Mixed_mothly_compensation', sa.String(length=120), nullable=False),
    sa.Column('Mixed_anual_compensation', sa.String(length=120), nullable=False),
    sa.Column('Assistance_bonus', sa.Boolean(), nullable=False),
    sa.Column('Production_bonus', sa.Boolean(), nullable=False),
    sa.Column('Transport_bonus', sa.Boolean(), nullable=False),
    sa.Column('Savings_Bank', sa.Boolean(), nullable=False),
    sa.Column('sales_commissions', sa.Boolean(), nullable=False),
    sa.Column('parking_payment', sa.Boolean(), nullable=False),
    sa.Column('full_H_C_M_Emp_Family', sa.Boolean(), nullable=False),
    sa.Column('partial_H_C_M_Emp_Family', sa.Boolean(), nullable=False),
    sa.Column('Funeral_Insurance', sa.Boolean(), nullable=False),
    sa.Column('Vehicle_insurance', sa.Boolean(), nullable=False),
    sa.Column('life_insurance', sa.Boolean(), nullable=False),
    sa.Column('dinning_room', sa.Boolean(), nullable=False),
    sa.Column('food_bags', sa.Boolean(), nullable=False),
    sa.Column('uniform', sa.Boolean(), nullable=False),
    sa.Column('birthday_bonus', sa.Boolean(), nullable=False),
    sa.Column('vacational_plans', sa.Boolean(), nullable=False),
    sa.Column('Seniority_premium', sa.Boolean(), nullable=False),
    sa.Column('children_premium', sa.Boolean(), nullable=False),
    sa.Column('proffesion_premium', sa.Boolean(), nullable=False),
    sa.Column('december_gift', sa.Boolean(), nullable=False),
    sa.Column('Gym', sa.Boolean(), nullable=False),
    sa.Column('School_scholarships', sa.Boolean(), nullable=False),
    sa.Column('school_supplies', sa.Boolean(), nullable=False),
    sa.Column('marriage_bonus', sa.Boolean(), nullable=False),
    sa.Column('birth_bonus', sa.Boolean(), nullable=False),
    sa.Column('Vehicle_Credit', sa.Boolean(), nullable=False),
    sa.Column('Mortgage_credit', sa.Boolean(), nullable=False),
    sa.Column('Psychological_Test', sa.Integer(), nullable=False),
    sa.Column('Technical_knowledge_test', sa.Integer(), nullable=False),
    sa.Column('Business_knowledge_test', sa.Integer(), nullable=False),
    sa.Column('Other_tests', sa.Integer(), nullable=False),
    sa.Column('Global_Average', sa.Integer(), nullable=False),
    sa.Column('References_Check', sa.String(length=120), nullable=False),
    sa.Column('Technical_Test_Results', sa.Integer(), nullable=False),
    sa.Column('Observations', sa.String(length=120), nullable=False),
    sa.Column('Days_passed_requisition_interviewGH', sa.String(length=120), nullable=False),
    sa.Column('Days_passed_interviewGH_Techinterview', sa.String(length=120), nullable=False),
    sa.Column('Days_passed_Techinterview_entry', sa.String(length=120), nullable=False),
    sa.Column('Days_passed_requisition_entry', sa.String(length=120), nullable=False),
    sa.Column('Days_passed_open_status', sa.String(length=120), nullable=False),
    sa.Column('Checking_Records_Detail', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker')
    op.drop_table('user')
    # ### end Alembic commands ###
