"""empty message

Revision ID: c1f35d851e40
Revises: 
Create Date: 2021-04-11 15:00:46.712094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f35d851e40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('salt', sa.String(length=120), nullable=True),
    sa.Column('hashed_password', sa.String(length=120), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('init_date', sa.String(length=80), nullable=True),
    sa.Column('Consultor', sa.String(length=80), nullable=True),
    sa.Column('candidate', sa.String(length=80), nullable=True),
    sa.Column('cedula', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('phone_number', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('catchment_source', sa.String(length=120), nullable=True),
    sa.Column('managment', sa.String(length=120), nullable=True),
    sa.Column('vacant', sa.String(length=120), nullable=True),
    sa.Column('interview_date', sa.String(length=120), nullable=True),
    sa.Column('actual_charge', sa.String(length=120), nullable=True),
    sa.Column('company', sa.String(length=120), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('coin', sa.Integer(), nullable=True),
    sa.Column('basic_salary', sa.Integer(), nullable=True),
    sa.Column('variable_salary', sa.Integer(), nullable=True),
    sa.Column('cesta_ticket', sa.Integer(), nullable=True),
    sa.Column('Profit_Days', sa.Integer(), nullable=True),
    sa.Column('vacations', sa.Integer(), nullable=True),
    sa.Column('Vacation_Bonus', sa.Integer(), nullable=True),
    sa.Column('Factor', sa.String(length=120), nullable=True),
    sa.Column('Estimated_annual_package', sa.String(length=120), nullable=True),
    sa.Column('Observations', sa.String(length=300), nullable=True),
    sa.Column('Production_bonus', sa.String(length=120), nullable=True),
    sa.Column('Transport_bonus', sa.String(length=120), nullable=True),
    sa.Column('Savings_Bank', sa.String(length=120), nullable=True),
    sa.Column('parking_payment', sa.String(length=120), nullable=True),
    sa.Column('full_HCM_Emp_Family', sa.String(length=120), nullable=True),
    sa.Column('partial_HCM_Emp_Family', sa.String(length=120), nullable=True),
    sa.Column('Vehicle_insurance', sa.String(length=120), nullable=True),
    sa.Column('life_insurance', sa.String(length=120), nullable=True),
    sa.Column('dinning_room', sa.String(length=120), nullable=True),
    sa.Column('food_bags', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker')
    op.drop_table('user')
    # ### end Alembic commands ###
