"""empty message

Revision ID: d961e8a5621f
Revises: 14d23ef36d13
Create Date: 2021-03-01 14:45:59.144550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd961e8a5621f'
down_revision = '14d23ef36d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('Business_knowledge_test', sa.Integer(), nullable=False))
    op.add_column('worker', sa.Column('Checking_Records_Detail', sa.String(length=120), nullable=False))
    op.add_column('worker', sa.Column('Days_passed_Techinterview_entry', sa.String(length=120), nullable=False))
    op.add_column('worker', sa.Column('Days_passed_interviewGH_Techinterview', sa.String(length=120), nullable=False))
    op.add_column('worker', sa.Column('Days_passed_open_status', sa.String(length=120), nullable=False))
    op.add_column('worker', sa.Column('Days_passed_requisition_entry', sa.String(length=120), nullable=False))
    op.add_column('worker', sa.Column('Days_passed_requisition_interviewGH', sa.String(length=120), nullable=False))
    op.add_column('worker', sa.Column('Global_Average', sa.Integer(), nullable=False))
    op.add_column('worker', sa.Column('Gym', sa.Boolean(), nullable=False))
    op.add_column('worker', sa.Column('Mortgage_credit', sa.Boolean(), nullable=False))
    op.add_column('worker', sa.Column('Observations', sa.String(length=120), nullable=False))
    op.add_column('worker', sa.Column('Other_tests', sa.Integer(), nullable=False))
    op.add_column('worker', sa.Column('Psychological_Test', sa.Integer(), nullable=False))
    op.add_column('worker', sa.Column('References_Check', sa.Boolean(), nullable=False))
    op.add_column('worker', sa.Column('School_scholarships', sa.Boolean(), nullable=False))
    op.add_column('worker', sa.Column('Seniority_premium', sa.Boolean(), nullable=False))
    op.add_column('worker', sa.Column('Technical_Test_Results', sa.Boolean(), nullable=False))
    op.add_column('worker', sa.Column('Technical_knowledge_test', sa.Integer(), nullable=False))
    op.add_column('worker', sa.Column('Vehicle_Credit', sa.Boolean(), nullable=False))
    op.add_column('worker', sa.Column('birth_bonus', sa.Boolean(), nullable=False))
    op.add_column('worker', sa.Column('birthday_bonus', sa.Boolean(), nullable=False))
    op.add_column('worker', sa.Column('children_premium', sa.Boolean(), nullable=False))
    op.add_column('worker', sa.Column('december_gift', sa.Boolean(), nullable=False))
    op.add_column('worker', sa.Column('dinning_room', sa.Boolean(), nullable=False))
    op.add_column('worker', sa.Column('food_bags', sa.Boolean(), nullable=False))
    op.add_column('worker', sa.Column('marriage_bonus', sa.Boolean(), nullable=False))
    op.add_column('worker', sa.Column('proffesion_premium', sa.Boolean(), nullable=False))
    op.add_column('worker', sa.Column('school_supplies', sa.Boolean(), nullable=False))
    op.add_column('worker', sa.Column('uniform', sa.Boolean(), nullable=False))
    op.add_column('worker', sa.Column('vacational_plans', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'worker', ['Days_passed_open_status'])
    op.create_unique_constraint(None, 'worker', ['Checking_Records_Detail'])
    op.create_unique_constraint(None, 'worker', ['Observations'])
    op.create_unique_constraint(None, 'worker', ['Days_passed_requisition_interviewGH'])
    op.create_unique_constraint(None, 'worker', ['Days_passed_interviewGH_Techinterview'])
    op.create_unique_constraint(None, 'worker', ['Days_passed_Techinterview_entry'])
    op.create_unique_constraint(None, 'worker', ['Days_passed_requisition_entry'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worker', type_='unique')
    op.drop_constraint(None, 'worker', type_='unique')
    op.drop_constraint(None, 'worker', type_='unique')
    op.drop_constraint(None, 'worker', type_='unique')
    op.drop_constraint(None, 'worker', type_='unique')
    op.drop_constraint(None, 'worker', type_='unique')
    op.drop_constraint(None, 'worker', type_='unique')
    op.drop_column('worker', 'vacational_plans')
    op.drop_column('worker', 'uniform')
    op.drop_column('worker', 'school_supplies')
    op.drop_column('worker', 'proffesion_premium')
    op.drop_column('worker', 'marriage_bonus')
    op.drop_column('worker', 'food_bags')
    op.drop_column('worker', 'dinning_room')
    op.drop_column('worker', 'december_gift')
    op.drop_column('worker', 'children_premium')
    op.drop_column('worker', 'birthday_bonus')
    op.drop_column('worker', 'birth_bonus')
    op.drop_column('worker', 'Vehicle_Credit')
    op.drop_column('worker', 'Technical_knowledge_test')
    op.drop_column('worker', 'Technical_Test_Results')
    op.drop_column('worker', 'Seniority_premium')
    op.drop_column('worker', 'School_scholarships')
    op.drop_column('worker', 'References_Check')
    op.drop_column('worker', 'Psychological_Test')
    op.drop_column('worker', 'Other_tests')
    op.drop_column('worker', 'Observations')
    op.drop_column('worker', 'Mortgage_credit')
    op.drop_column('worker', 'Gym')
    op.drop_column('worker', 'Global_Average')
    op.drop_column('worker', 'Days_passed_requisition_interviewGH')
    op.drop_column('worker', 'Days_passed_requisition_entry')
    op.drop_column('worker', 'Days_passed_open_status')
    op.drop_column('worker', 'Days_passed_interviewGH_Techinterview')
    op.drop_column('worker', 'Days_passed_Techinterview_entry')
    op.drop_column('worker', 'Checking_Records_Detail')
    op.drop_column('worker', 'Business_knowledge_test')
    # ### end Alembic commands ###
