"""empty message

Revision ID: e92f6cde8d49
Revises: 3b3585624d21
Create Date: 2021-03-19 13:30:30.898943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e92f6cde8d49'
down_revision = '3b3585624d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worker', 'Observations',
               existing_type=mysql.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worker', 'Observations',
               existing_type=mysql.VARCHAR(length=300),
               nullable=False)
    # ### end Alembic commands ###
