"""empty message

Revision ID: f8ce307f0396
Revises: 314d709f77b3
Create Date: 2021-03-02 13:28:58.488124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ce307f0396'
down_revision = '314d709f77b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('Academic_level', table_name='worker')
    op.drop_index('Checking_Records_Detail', table_name='worker')
    op.drop_index('Current_courses', table_name='worker')
    op.drop_index('Days_passed_Techinterview_entry', table_name='worker')
    op.drop_index('Days_passed_interviewGH_Techinterview', table_name='worker')
    op.drop_index('Days_passed_open_status', table_name='worker')
    op.drop_index('Days_passed_requisition_entry', table_name='worker')
    op.drop_index('Days_passed_requisition_interviewGH', table_name='worker')
    op.drop_index('Estimated_annual_package', table_name='worker')
    op.drop_index('Factor', table_name='worker')
    op.drop_index('Mixed_anual_compensation', table_name='worker')
    op.drop_index('Mixed_mothly_compensation', table_name='worker')
    op.drop_index('Monthly_Cash_Flow', table_name='worker')
    op.drop_index('Observations', table_name='worker')
    op.drop_index('Place_of_residence', table_name='worker')
    op.drop_index('Profit_Days', table_name='worker')
    op.drop_index('Reason', table_name='worker')
    op.drop_index('References_Check_date', table_name='worker')
    op.drop_index('Salary_Aspirations', table_name='worker')
    op.drop_index('Software_Hardware_ERP_knowledge', table_name='worker')
    op.drop_index('Technical_Interview_date', table_name='worker')
    op.drop_index('Vacation_Bonus', table_name='worker')
    op.drop_index('actual_charge', table_name='worker')
    op.drop_index('admission_date', table_name='worker')
    op.drop_index('availability', table_name='worker')
    op.drop_index('basic_salary', table_name='worker')
    op.drop_index('branch_office', table_name='worker')
    op.drop_index('catchment_source', table_name='worker')
    op.drop_index('cesta_ticket', table_name='worker')
    op.drop_index('coin', table_name='worker')
    op.drop_index('company', table_name='worker')
    op.drop_index('current_employment_contract', table_name='worker')
    op.drop_index('email', table_name='worker')
    op.drop_index('experience_years', table_name='worker')
    op.drop_index('interview_date', table_name='worker')
    op.drop_index('managment', table_name='worker')
    op.drop_index('name_work_person', table_name='worker')
    op.drop_index('preemployment_test_date', table_name='worker')
    op.drop_index('salary_offer_date', table_name='worker')
    op.drop_index('sector', table_name='worker')
    op.drop_index('vacant', table_name='worker')
    op.drop_index('vacations', table_name='worker')
    op.drop_index('variable_salary', table_name='worker')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('variable_salary', 'worker', ['variable_salary'], unique=True)
    op.create_index('vacations', 'worker', ['vacations'], unique=True)
    op.create_index('vacant', 'worker', ['vacant'], unique=True)
    op.create_index('sector', 'worker', ['sector'], unique=True)
    op.create_index('salary_offer_date', 'worker', ['salary_offer_date'], unique=True)
    op.create_index('preemployment_test_date', 'worker', ['preemployment_test_date'], unique=True)
    op.create_index('name_work_person', 'worker', ['name_work_person'], unique=True)
    op.create_index('managment', 'worker', ['managment'], unique=True)
    op.create_index('interview_date', 'worker', ['interview_date'], unique=True)
    op.create_index('experience_years', 'worker', ['experience_years'], unique=True)
    op.create_index('email', 'worker', ['email'], unique=True)
    op.create_index('current_employment_contract', 'worker', ['current_employment_contract'], unique=True)
    op.create_index('company', 'worker', ['company'], unique=True)
    op.create_index('coin', 'worker', ['coin'], unique=True)
    op.create_index('cesta_ticket', 'worker', ['cesta_ticket'], unique=True)
    op.create_index('catchment_source', 'worker', ['catchment_source'], unique=True)
    op.create_index('branch_office', 'worker', ['branch_office'], unique=True)
    op.create_index('basic_salary', 'worker', ['basic_salary'], unique=True)
    op.create_index('availability', 'worker', ['availability'], unique=True)
    op.create_index('admission_date', 'worker', ['admission_date'], unique=True)
    op.create_index('actual_charge', 'worker', ['actual_charge'], unique=True)
    op.create_index('Vacation_Bonus', 'worker', ['Vacation_Bonus'], unique=True)
    op.create_index('Technical_Interview_date', 'worker', ['Technical_Interview_date'], unique=True)
    op.create_index('Software_Hardware_ERP_knowledge', 'worker', ['Software_Hardware_ERP_knowledge'], unique=True)
    op.create_index('Salary_Aspirations', 'worker', ['Salary_Aspirations'], unique=True)
    op.create_index('References_Check_date', 'worker', ['References_Check_date'], unique=True)
    op.create_index('Reason', 'worker', ['Reason'], unique=True)
    op.create_index('Profit_Days', 'worker', ['Profit_Days'], unique=True)
    op.create_index('Place_of_residence', 'worker', ['Place_of_residence'], unique=True)
    op.create_index('Observations', 'worker', ['Observations'], unique=True)
    op.create_index('Monthly_Cash_Flow', 'worker', ['Monthly_Cash_Flow'], unique=True)
    op.create_index('Mixed_mothly_compensation', 'worker', ['Mixed_mothly_compensation'], unique=True)
    op.create_index('Mixed_anual_compensation', 'worker', ['Mixed_anual_compensation'], unique=True)
    op.create_index('Factor', 'worker', ['Factor'], unique=True)
    op.create_index('Estimated_annual_package', 'worker', ['Estimated_annual_package'], unique=True)
    op.create_index('Days_passed_requisition_interviewGH', 'worker', ['Days_passed_requisition_interviewGH'], unique=True)
    op.create_index('Days_passed_requisition_entry', 'worker', ['Days_passed_requisition_entry'], unique=True)
    op.create_index('Days_passed_open_status', 'worker', ['Days_passed_open_status'], unique=True)
    op.create_index('Days_passed_interviewGH_Techinterview', 'worker', ['Days_passed_interviewGH_Techinterview'], unique=True)
    op.create_index('Days_passed_Techinterview_entry', 'worker', ['Days_passed_Techinterview_entry'], unique=True)
    op.create_index('Current_courses', 'worker', ['Current_courses'], unique=True)
    op.create_index('Checking_Records_Detail', 'worker', ['Checking_Records_Detail'], unique=True)
    op.create_index('Academic_level', 'worker', ['Academic_level'], unique=True)
    # ### end Alembic commands ###
